### ISSUE TITLE
AWS CodeDeploy를 이용한 자동화 배포 시 NPM이 정상적으로 동작하지 않는 오류

### ISSUE THREAD

**Issue by choi3179** [T2-Papillon/front-vue#93]
### Github action으로 S3 정상 배포
![image](https://github.com/T2-Papillon/front-vue/assets/66417882/fc160b45-9f71-4cbd-bb8a-a9f65ecd7deb)
### EC2 내부 동작
- CodeDeploy가 정상적으로 진행된 후 실행되는 sh 실행 파일
``` sh
#!/usr/bin/env bash

cd /home/ubuntu/app/papplan

# 터미널 로그 확인
# set -x

# vue 프로젝트 빌드
npm install
npm run build

# 생성된 빌드 파일의 소유자 변경
sudo chown -R ubuntu:ubuntu dist

# public 디렉토리의 권한 변경
sudo chmod -R +w public

sudo docker compose -f docker-compose.yml up -d --build --force-recreate
```
 - npm으로 vite 빌드 시 생성되는 정적 파일 모음인 dist 디렉토리의 권한이 root:root로 생성됨으로 인해 nginx docker container로 해당 디렉토리 volume을 생성할 수 없는 문제
 - dist 디렉토리는 생성되었지만 정적 파일이 생성되지 않는 문제
### appspec.yml
 ```yaml
version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/app/papplan
      overwrite: yes

permissions:
    - object: /
      pattern: '**'
      owner: ubuntu
      group: ubuntu

hooks:
    AfterInstall:
        - location: stop.sh
          timeout: 60
          runas: ubuntu
    ApplicationStart:
        - location: start.sh
          timeout: 60
          runas: ubuntu
``` 
### docker-compose.yml
```yaml
version: '3'

services:
  nginx_server:
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d
    ports:
      - "5174:80"
    restart: always
```
### nginx 설정 파일(nginx.conf)
```conf
server {
    listen 80;

    # 로그 파일 위치 설정
    access_log /var/log/nginx/vue_app_access.log;
    error_log /var/log/nginx/vue_app_error.log;

    # 정적 파일과 index.html 서빙
    root /usr/share/nginx/html;
    index index.html;

    # 모든 요청을 Vue 앱으로 리다이렉트
    location / {
        try_files $uri $uri/ /index.html;
	# CORS 설정
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept';
    }
}
```
- 컨테이너와 nginx 웹 서버는 정상적으로 실행중

**Comment by choi3179** [comment]
## 해결방법
- **npm 명령을 workflow에서 실행**
### .github/workflows/action.dev.yml 수정
```yml
name: Deploy2aws 🚀

on:
    push:
        branches:
            - dev
    pull_request:
        types:
            - closed

jobs:
    deploy:
        environment: dev
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # node 버전 세팅 - local 버전과 일치 
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.11.0'
  
            # 환경 변수 파일 생성 - Github secrets로 히든 처리
            - name: Create .env.production file
              run: |
                  echo "VITE_APP_TITLE=production" > .env.production && \
                  echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production

            - name: Install dependencies
              run: npm install

            # npm 빌드
            - name: Build Vue project
              run: npm run build

            # AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ vars.AWS_REGION }}

            # 빌드 결과물을 S3 버킷에 업로드
            - name: Upload to AWS S3
              run: |
                  aws deploy push \
                    --application-name ${{ vars.CODE_DEPLOY_APP_NAME }} \
                    --ignore-hidden-files \
                    --s3-location s3://${{ vars.S3_BUCKET_NAME }}/$GITHUB_SHA.zip \
                    --source .

            # S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
            - name: Deploy to AWS EC2 from S3
              run: |
                  aws deploy create-deployment \
                    --application-name ${{ vars.CODE_DEPLOY_APP_NAME }} \
                    --deployment-config-name CodeDeployDefault.AllAtOnce \
                    --deployment-group-name ${{ vars.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
                    --s3-location bucket=${{ vars.S3_BUCKET_NAME }},key=$GITHUB_SHA.zip,bundleType=zip

```
- npm 관련 동작을 workflow로 이동 후 생성된 정적파일과 환경 변수 파일을 한번에 EC2에 배포
- dist 디렉토리 소유자 ubuntu:ubuntu 확인
![image](https://github.com/T2-Papillon/front-vue/assets/66417882/dd3de5a2-8b3e-416c-a901-10e986276ed0)
- 배포 정상 테스트 완료
